language: cpp

matrix:
    include:
        - name: "Linux, Release"
          os: linux
          dist: xenial
          sudo: required
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=gcc-cxx14-c11.cmake
              - Qt5_DIR="/opt/qt512/lib/cmake/Qt5"
        - name: "macOS, Release"
          os: osx
          osx_image: xcode10.2
          env:
              - CMAKE_GENERATOR_NAME="Unix Makefiles"
              - CMAKE_BUILD_TYPE="Release"
              - CMAKE_TOOLCHAIN_FILE_NAME=clang-cxx14.cmake
              - Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5"

addons:
    apt: # Linux
        packages:
            - build-essential
            - cmake
            - git
            - libgl1-mesa-dev
            - qt512-meta-full
            - unzip
            - wget
            - rpm
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:beineri/opt-qt-5.12.3-xenial"
    homebrew: # macOS
        packages:
            - cmake
            - git
            - qt5

cache:
    directories:
        - $HOME/.hunter

script:
    - mkdir ./build && cd ./build
    - >
        cmake -G "$CMAKE_GENERATOR_NAME"
        -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
        -DCMAKE_TOOLCHAIN_FILE=cmake/polly/$CMAKE_TOOLCHAIN_FILE_NAME
        -DBUILD_ALL:BOOL=TRUE
        ..
    - cmake --build . --config $CMAKE_BUILD_TYPE -- -j 2
    - cpack -C $CMAKE_BUILD_TYPE

deploy:
    provider: releases # GitHub Releases
    api_key:
        secure: "EF8QAyupLh7Okc5Kefg7F4Sqz3ybJ/K84uDwfUo1BMTzNHP57tFmcDnJvnieP0nZ/4Nh8mElFaWCnRXG4vISpjGdC1x1hqv1uaNxnHSAAuir3l8KtliWQDvQ+E7+9LKXFdjz2a7Pd/zWuDRRPmYiXLSIi4iRzKjPXTQkRYvNUWbLxXt299ppcIx2UV+9v+2OJ0vhypiE1AFLUJVNxAvC6EkAFA2C4TF7nbK5OufDGgsN+nJKdIPzppI5tzErqkp1tRVbaEVBlsRyMmggiVClH85epjMuJ8ZXYE4z4QoTcpQzp+u3ZtZTDJAaeDtQiU7weuBjF49oeCaxtCn/XVPsGmXbJOR/xK6O84dHoxFdll14TwiJn3YPo4vrVAdtlMcWZ6USWgzC33pM0KIkoKIYmJdXI9EVwnN+udIOkLYjgAuxyu5LXirp3EDTP5LcdRybHma8jjTcmNku3wuNSNiUKEFYGQ40nDrf/2uP8VzCdPoanfLspIVk4/y+Q2rs8Ht8yC5rXdUfL1FeP1zyWxyXoSWm5jxNc5xWHd9bxdBhTcTwGYRK7nyY3gqjVdLNsOaULwQpc5RdsEZ1vfORj+NYLQ/kljHL7vo9tmB4I4T9dCEK0FtKauCIZhcphsNgwJetiSO0oCWslV+11zSUjC80G4PR6bp2uHMW1bxZ62QeXv8="
    file: dist/qwertycoin-zero-* # path is relative to the current working directory, not to $TRAVIS_BUILD_DIR
    file_glob: true
    draft: true
    on:
        branch: master
        tags: true
        condition: $CMAKE_BUILD_TYPE = "Release"
    skip_cleanup: true
